"""
Pydantic models for the AI Proof-of-Fix remediation pipeline.

These models define the structured data flowing through:
  Evidence → AI Remediation → Verification → Proof-of-Fix
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class FixStatus(str, Enum):
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"


class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


# ---------------------------------------------------------------------------
# Evidence models — input to the AI
# ---------------------------------------------------------------------------

class CheckovFinding(BaseModel):
    """A single Checkov failed check, distilled to essentials."""

    check_id: str
    check_name: str
    severity: Severity
    resource: str = ""
    category: str = "General"
    guideline: str = ""


class AttackPathStep(BaseModel):
    """One node in an attack path sequence."""

    node: str
    action: str = ""


class AttackPath(BaseModel):
    """A complete attack path from entry to crown jewel."""

    path: list[str]
    steps: list[AttackPathStep] = Field(default_factory=list)
    impact: str = ""
    severity: Severity = Severity.HIGH


class IAMRisk(BaseModel):
    """A detected IAM risk."""

    risk_type: str
    severity: Severity
    detail: str
    resource: str = ""


class CrownJewel(BaseModel):
    """A sensitive target resource."""

    resource_id: str
    resource_type: str
    reason: str


class ResourceRelationship(BaseModel):
    """An edge in the infrastructure graph."""

    source: str
    target: str
    relationship: str
    risk_level: str = "medium"


class SecurityEvidence(BaseModel):
    """Structured security evidence assembled from deterministic analysis.

    This is the ONLY input the AI receives.
    """

    checkov_findings: list[CheckovFinding] = Field(default_factory=list)
    attack_paths: list[AttackPath] = Field(default_factory=list)
    iam_risks: list[IAMRisk] = Field(default_factory=list)
    crown_jewels: list[CrownJewel] = Field(default_factory=list)
    resource_relationships: list[ResourceRelationship] = Field(
        default_factory=list
    )

    resource_count: int = 0
    blast_radius_score: int = 0
    highest_risk_nodes: list[str] = Field(default_factory=list)

    # Summary stats
    total_findings: int = 0
    critical_findings: int = 0
    high_findings: int = 0
    total_attack_paths: int = 0
    critical_attack_paths: int = 0


# ---------------------------------------------------------------------------
# Remediation models — AI output
# ---------------------------------------------------------------------------

class RemediationCandidate(BaseModel):
    """A structured remediation proposal generated by the AI."""

    id: str = Field(default_factory=lambda: str(uuid4()))

    target_issue: str

    target_check_ids: list[str] = Field(
        default_factory=list
    )

    explanation: str

    proposed_change: str

    terraform_patch: str

    expected_effect: str

    confidence: float = 0.8

    attempt_number: int = 1

    generation_method: str = "llm"


# ---------------------------------------------------------------------------
# Verification models — deterministic engine output
# ---------------------------------------------------------------------------

class HCLValidationResult(BaseModel):
    """Result of HCL syntax validation."""

    valid: bool
    error_message: str = ""
    resource_count: int = 0


class CheckovRescanResult(BaseModel):
    """Result of re-running Checkov on patched HCL."""

    failed_count: int = 0
    passed_count: int = 0
    original_failed_count: int = 0

    findings_resolved: list[str] = Field(
        default_factory=list
    )

    new_findings: list[str] = Field(
        default_factory=list
    )


class AttackPathComparison(BaseModel):
    """Comparison of attack paths before and after remediation."""

    attack_paths_before: int = 0
    attack_paths_after: int = 0

    critical_before: int = 0
    critical_after: int = 0

    paths_broken: int = 0

    paths_remaining: list[list[str]] = Field(
        default_factory=list
    )

    new_paths: list[list[str]] = Field(
        default_factory=list
    )

    blast_radius_before: int = 0
    blast_radius_after: int = 0


class ComplianceVerificationResult(BaseModel):
    """Deterministic before/after compliance verification."""

    original_controls: list[str] = Field(
        default_factory=list
    )

    resolved_controls: list[str] = Field(
        default_factory=list
    )

    remaining_controls: list[str] = Field(
        default_factory=list
    )

    passed: bool = True

    detail: str = ""


class ValidationStep(BaseModel):
    """A single step in the verification pipeline."""

    name: str

    status: str  # "passed", "failed", "skipped"

    detail: str = ""


class ValidationResult(BaseModel):
    """Complete result of the verification pipeline."""

    overall_status: str  # "PASSED" or "FAILED"

    hcl_validation: HCLValidationResult

    checkov_rescan: CheckovRescanResult

    attack_path_comparison: AttackPathComparison

    compliance_verification: ComplianceVerificationResult = Field(
        default_factory=ComplianceVerificationResult
    )

    regression_check_passed: bool = False

    steps: list[ValidationStep] = Field(
        default_factory=list
    )

    failure_reasons: list[str] = Field(
        default_factory=list
    )


# ---------------------------------------------------------------------------
# Proof-of-Fix — the final attestation
# ---------------------------------------------------------------------------

class ProofOfFix(BaseModel):
    """Structured attestation that a specific remediation passed verification.

    IMPORTANT:
    We claim "This specific remediation passed our defined
    verification pipeline" — NOT "the infrastructure is proven secure".
    """

    id: str = Field(
        default_factory=lambda: str(uuid4())
    )

    status: FixStatus = FixStatus.PENDING

    target_issue: str = ""

    target_check_ids: list[str] = Field(
        default_factory=list
    )

    # -----------------------------------------------------------------------
    # Before / after comparison
    # -----------------------------------------------------------------------

    original_attack_paths: int = 0

    new_attack_paths: int = 0

    paths_eliminated: int = 0

    original_failed_checks: int = 0

    new_failed_checks: int = 0

    checks_resolved: int = 0

    # -----------------------------------------------------------------------
    # Verification results
    # -----------------------------------------------------------------------

    terraform_valid: bool = False

    checkov_passed: bool = False

    attack_paths_reduced: bool = False

    compliance_verified: bool = False

    no_regression: bool = False

    # -----------------------------------------------------------------------
    # Compliance evidence
    # -----------------------------------------------------------------------

    compliance_controls_resolved: list[str] = Field(
        default_factory=list
    )

    compliance_controls_remaining: list[str] = Field(
        default_factory=list
    )

    # -----------------------------------------------------------------------
    # Artifacts
    # -----------------------------------------------------------------------

    original_hcl_hash: str = ""

    patched_hcl_hash: str = ""

    patched_hcl: str = ""

    # -----------------------------------------------------------------------
    # Metadata
    # -----------------------------------------------------------------------

    verification_timestamp: str = Field(
        default_factory=lambda: datetime.now(
            timezone.utc
        ).isoformat()
    )

    attempts_used: int = 0

    max_attempts: int = 3

    generation_method: str = "llm"

    # -----------------------------------------------------------------------
    # Detailed steps for UI display
    # -----------------------------------------------------------------------

    verification_steps: list[ValidationStep] = Field(
        default_factory=list
    )

    failure_reasons: list[str] = Field(
        default_factory=list
    )

    # -----------------------------------------------------------------------
    # Remediation and validation
    # -----------------------------------------------------------------------

    remediation: RemediationCandidate | None = None

    validation: ValidationResult | None = None
